FROM ubuntu:latest
ENV MEMCACHED_USER=memcached \
    MEMCACHED_VERSION=1.5.6 \
    MEMCACHED_SHA1=fe6ac14e6e98d4b7ff8293cea359b21342bc9c68
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
      memcached=${MEMCACHED_VERSION}* \
 && sed 's/^-d/# -d/' -i /etc/memcached.conf \
 && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /sbin/entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh

EXPOSE 11211/tcp 11211/udp
ENTRYPOINT ["/sbin/entrypoint.sh"]
CMD ["/usr/bin/memcached"]


env: 
          - name: EMAIL_NOREPLY
            value: noreply@yourdomain.com
          - name: EMAIL_SMTP_HOST
            value: smtp.gmail.com
          - name: EMAIL_SMTP_PORT
            value: 587
          - name: EMAIL_SMTP_USERNAME
            value: benamorelyes0@gmail.com
          - name: EMAIL_SMTP_PASSWORD
            value: Azertyuiop123456789.
          #EMAIL_SMTP_SSL: enable
          # GitHub
          - name: OAUTH_GITHUB_CLIENTID
            value: 8bf25d5a40548ac247a8
          - name: OAUTH_GITHUB_SECRET
            value: 853a873ea6902c26369e1187c142fbacb03a46d5