version: '2'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
    - pgdb:/var/lib/redis
    restart: always
      
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
     - pgdb:/var/lib/postgres/data
     - pgdb:/etc/postgresql
     - pgdb:/var/log/postgresql
     - pgdb:/var/lib/postgresql
  
  fider:
    restart: always
    image: getfider/fider:stable
    ports:
      - "9999:3000"
    links:
     - redis
     - postgres
    depends_on:
     - redis
     - postgres
    environment: 
      DATABASE_URL: postgres://fider:fider@postgres:5432/fider?sslmode=disable
      JWT_SECRET: xxxxx
      EMAIL_NOREPLY: noreply@yourdomain.com
      EMAIL_SMTP_HOST: smtp.gmail.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USERNAME: xxxxx
      EMAIL_SMTP_PASSWORD: xxxx
      #EMAIL_SMTP_SSL: enable
      # GitHub
      OAUTH_GITHUB_CLIENTID: xxxx
      OAUTH_GITHUB_SECRET: xxxxx

volumes:
  pgdb: