apiVersion: v1
kind: Service
metadata:
  name: fider
  labels:
    app: fider
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 3000
  selector:
    app: fider
status:
  loadBalancer: {}
